name: Run Docker Compose in GitHub Actions

on:
  workflow_dispatch:
  repository_dispatch:
    types: [trigger-ratting-workflow]

jobs:
  run-docker-compose:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Pull Docker Images
      run: |
        docker pull ravi88881/my-ratting-app-image:latest
        docker pull ravi8881/solr-compile-code-app-image:latest
        docker pull ravi8881/my-graphql-code-app-image:latest

    - name: Run Docker Compose
      run: docker-compose up --build -d
